### ISSUE TITLE
создать веб прокси

### ISSUE THREAD

**Issue by nosovk** [AndriiPolishko/Dopka#1]
1. на главной странице сервиса у человека доступен тектовый инпут для ввода http адреса страницы
2. человек вводит урл и нажимает просмотреть
3. бекенд делает запрос на заданный урл, выкачивает его, и отдает выкачанный html клинету
4. клиент рендерит страницу в изолированном контейнере

- бекенду необходимо делать несколько дополнительных операций - подменять урлы с урлов оригинального сервера на свои.
- корректно обрабатывать mime tipe содержимого

Проверочный кейс: мы просим показать нам главную страницу пары сайтов и смотрим чтобы при этом не было запросов к оригинальному домену ресурса из браузера клиента.

**Comment by nosovk** [comment]
https://www.mailcheck.co/
пример тестового урла

**Comment by nosovk** [comment]
https://eu11.proxysite.com/process.php?d=Z%2FPiMzd3hF4v57CTAfx5Z66oYKQ%3D&b=1&f=norefer
пример готового сервиса

**Comment by AndriiPolishko** [comment]
web http proxy

**Comment by nosovk** [comment]
iframe, http web proxy, nodejs http stream, transform stream, mime type, http headers
